{
 "title": "Oracledb监控-性能与表空间 by kk v2",
 "description": "使用oracledb-exporter进行oracle数据库监控，相对其他dashboard增加了tablespace的监控，可拓展设置为表空间告警；\n\n",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "job", "label": "JOB", "query": { "query": "label_values(oracledb_up,job)" } },
   {
    "name": "host",
    "label": "host",
    "query": {
     "query": "label_values(oracledb_up{job=\"$job\"}, instance)"
    }
   },
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" }
  ]
 },
 "panels": [
  {
   "title": "数据库",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "数据库状态",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "oracledb_up{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "执行计数",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "oracledb_activity_execute_count{instance=\"$host\"}"
    }
   ]
  },
  {
   "title": "用户提交数",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "oracledb_activity_user_commits{instance=\"$host\"}"
    }
   ]
  },
  {
   "title": "表空间状态",
   "type": "table-old",
   "gridPos": { "h": 19, "w": 9, "x": 15, "y": 1 },
   "targets": [
    {
     "expr": "((oracledb_tablespace_bytes{instance=\"$host\"}-oracledb_tablespace_free{instance=\"$host\"})/oracledb_tablespace_max_bytes{instance=\"$host\"})"
    },
    {
     "expr": "(oracledb_tablespace_max_bytes{instance=\"$host\"}-oracledb_tablespace_bytes{instance=\"$host\"}+oracledb_tablespace_free{instance=\"$host\"})"
    }
   ]
  },
  {
   "title": "活动会话(USER)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "oracledb_sessions_value{instance=\"$host\",type=\"USER\"}"
    }
   ]
  },
  {
   "title": "进程计数",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 5, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "oracledb_process_count{instance=\"$host\"}",
     "legendFormat": "{{descr}} - 进程计数"
    }
   ]
  },
  {
   "title": "用户回滚",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 11, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "oracledb_activity_user_rollbacks{instance=\"$host\"}",
     "legendFormat": "{{descr}} - 用户回滚"
    }
   ]
  },
  {
   "title": "并发等待时间",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "oracledb_wait_time_concurrency{instance=\"$host\"}",
     "legendFormat": "{{descr}} - 并发等待时间"
    }
   ]
  },
  {
   "title": "提交等待时间",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 7, "y": 7 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "oracledb_wait_time_commit{instance=\"$host\"}",
     "legendFormat": "{{descr}} - 提交等待时间"
    }
   ]
  },
  {
   "title": "应用等待",
   "type": "graph",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "oracledb_wait_time_application{instance=\"$host\"}\t",
     "legendFormat": "{{descr}} - 应用等待"
    }
   ]
  },
  {
   "title": "网络等待",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 7, "y": 13 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "oracledb_wait_time_network{instance=\"$host\"}\t",
     "legendFormat": "{{descr}} - 网络等待"
    }
   ]
  },
  {
   "title": "系统I/O等待",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "oracledb_wait_time_system_io{instance=\"$host\"}",
     "legendFormat": "{{descr}} - 系统I/O等待"
    }
   ]
  },
  {
   "title": "用户I/O等待",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 7, "y": 18 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "oracledb_wait_time_user_io{instance=\"$host\"}\t",
     "legendFormat": "{{descr}} - 用户I/P等待"
    }
   ]
  },
  {
   "title": "资源利用率",
   "type": "graph",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "oracledb_resource_current_utilization{instance=\"$host\"}",
     "legendFormat": "资源利用率 - {{resource_name}} "
    }
   ]
  },
  {
   "title": "组态等待时间",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "oracledb_wait_time_configuration{instance=\"$host\"}",
     "legendFormat": "{{descr}} - 组态等待时间"
    }
   ]
  },
  {
   "title": "Scheduler 等待时间",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 7, "y": 24 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "oracledb_wait_time_scheduler{instance=\"$host\"}",
     "legendFormat": "{{descr}} - Scheduler 等待时间"
    }
   ]
  },
  {
   "title": "性能收集器状态",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "总收集",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "oracledb_exporter_scrapes_total{instance=\"$host\"}"
      }
     ]
    },
    {
     "title": "最后收集用时",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 3, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "oracledb_exporter_last_scrape_duration_seconds{instance=\"$host\"}\t"
      }
     ]
    }
   ]
  }
 ]
}